### ISSUE TITLE
Demo Links

### ISSUE THREAD

**Issue by hho** [jimrhoskins/ngmodules.org#6]
Every module should be able to supply a demo link displayed even on the overview page (maybe a demo button on the right or something). This may open the project home page (if the demos are there, like on the angular-ui homepage) or a JSfiddle if the module hasn't a demo UI itself.

**Comment by jimrhoskins** [comment]
This is excellent, and planned in some fashion. Ideally, I think it would be great if demo code could be packaged with the module itself, in some standard way, so a fiddle or plunk could be generated automatically from the source. This way the demo and source could be managed from one place. This turns out to be difficult. I've talked with the creator of plnkr.co about some ways to automate it, but so far we have some problems we are having trouble engineering around.

The other solution is to have a field to link to a page/plunk/fiddle that is just free-form. That might be the way to go until a better solution comes up.

I'm talking with the angular-ui team about some ideas for standardizing how modules are packaged, and demo code may be part of the discussion. 

Thoughts?

**Comment by jimrhoskins** [comment]
I'm going to close for now. I think adding a demo environment is out of scope for now. Links to plunker or jsbin/fiddle work for now
